apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  labels:
    component: web
spec:
  containers:
    - name: web
      image: dockerquark/journal-web-prod
      ports:
        - containerPort: 3000
